%% simulate_psf_image_gui.m
%  
%  small application to simulate image / set of images w/ same PSFs
%  but varying noise.
%
%  (very) basic process of recording a fluorescence image:
% 
%  (1) fluorophore excitation
%  (2) photon emission
%  (3) photon detection
%  (4) quantification & storage
%
%  2 key sources of imprecision that occur during fluorescence imaging:
% 
%  (1) blurring - light originating from some point cannot be focused back
%                 to a single point
%  (2) noise - random variance throughout captured image, due to randomness
%              of photon emission and imprecise determination of phtons 
%              emitted 
%
%  Blur is mathematically described by a convolution involving the
%  microscope's point spread function (PSF), which essentially acts like a
%  linear filter applied to the data.
% 
%  Points emitting light are replaced by their PSF, scaled according to
%  their individual brightness; where they overlap, detected intensities
%  add together.
%
%  Light originating from some observable point ends up being focused to
%  some larger volume (PSF), which has a minimum size based on light's
%  wavelength and the lens being used.
%  

%% interactive gui
%

SIM.MAIN = figure('units','normalized',...
                  'position',[0.275 0.33 0.45 0.36],...
                  'menubar','none',...
                  'toolbar','figure',...
                  'name','simulate_psf_image',...
                  'numbertitle','off',...
                  'resize','on');
%
SIM.dimension_panel = uipanel('units','normalized',...
                              'position',[0.02 0.675 0.48 0.3],...
                              'title','Image Dimensions',...
                              'fontweight','bold');
%
SIM.x_label = uicontrol('style','text',...
                        'parent',SIM.dimension_panel,...
                        'units','normalized',...
                        'position',[0.06 0.7 0.15 0.175],...
                        'string','X (pixels):',...
                        'horizontalalignment','left');
%
SIM.x_display = uicontrol('style','edit',...
                          'parent',SIM.dimension_panel,...
                          'units','normalized',...
                          'position',[0.24 0.7 0.25 0.225],...
                          'string',num2str(512));
%
SIM.y_label = uicontrol('style','text',...
                        'parent',SIM.dimension_panel,...
                        'units','normalized',...
                        'position',[0.06 0.45 0.15 0.175],...
                        'string','Y (pixels):',...
                        'horizontalalignment','left');
%
SIM.y_display = uicontrol('style','edit',...
                          'parent',SIM.dimension_panel,...
                          'units','normalized',...
                          'position',[0.24 0.45 0.25 0.225],...
                          'string',num2str(512));
%
SIM.z_label = uicontrol('style','text',...
                        'parent',SIM.dimension_panel,...
                        'units','normalized',...
                        'position',[0.06 0.2 0.15 0.175],...
                        'string','Z (slices):',...
                        'horizontalalignment','left');
%
SIM.z_display = uicontrol('style','edit',...
                          'parent',SIM.dimension_panel,...
                          'units','normalized',...
                          'position',[0.24 0.2 0.25 0.225],...
                          'string',num2str(64));
%
SIM.psf_panel = uipanel('units','normalized',...
                        'position',[0.02 0.35 0.48 0.3],...
                        'title','Point Spread Function',...
                        'fontweight','bold');
%
SIM.input_dir_label = uicontrol('style','text',...
                                'parent',SIM.psf_panel,...
                                'units','normalized',...
                                'position',[0.05 0.75 0.25 0.18],...
                                'string','Select Config. File',...
                                'horizontalalignment','left');
%
SIM.input_dir_loc = uicontrol('style','edit',...
                              'parent',SIM.psf_panel,...
                              'units','normalized',...
                              'position',[0.35 0.7 0.4 0.25],...
                              'enable','inactive',...
                              'visible','on',...
                              'backgroundcolor','white');
%
SIM.input_dir_button = uicontrol('style','push',...
                                 'parent',SIM.psf_panel,...
                                 'units','normalized',...
                                 'position',[0.77 0.7 0.2 0.25],...
                                 'enable','on',...
                                 'visible','on',...
                                 'string','Browse');
%
SIM.psf_number_label = uicontrol('style','text',...
                                 'parent',SIM.psf_panel,...
                                 'units','normalized',...
                                 'position',[0.06 0.2 0.15 0.175],...
                                 'enable','on',...
                                 'visible','on',...
                                 'string','# of PSFs:',...
                                 'horizontalalignment','left');
%
SIM.psf_number_input = uicontrol('style','edit',...
                                 'parent',SIM.psf_panel,...
                                 'units','normalized',...
                                 'position',[0.24 0.2 0.25 0.225],...
                                 'string',num2str(1500));
%
SIM.noise_panel = uipanel('units','normalized',...
                          'position',[0.02 0.025 0.48 0.3],...
                          'title','Noise / Background',...
                          'fontweight','bold');
%
SIM.noise_entry = uicontrol('style','text',...
                            'position',[0.02
%

%
%%%
%%%%%
%%%
%